# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180215_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='main.Author'),
        ),
    ]
